apiVersion: v2
name: rybbit
description: A Helm chart for Rybbit self-hosted analytics
type: application
version: 0.5.0
appVersion: "2.4.0"
kubeVersion: ">=1.19.0-0"
maintainers:
- name: cade
  email: cade.ayres@riskidev.fi
  url: https://github.com/Riskidev
keywords:
- analytics
- self-hosted
- rybbit
home: https://github.com/Riskidev/rybbit-helm
sources:
- https://github.com/Riskidev/rybbit-helm

dependencies:
- name: cluster
  alias: postgresql
  version: "0.6.0"
  repository: https://cloudnative-pg.github.io/charts
  condition: postgresql.enabled
  tags:
  - postgresql
- name: clickhouse
  version: "0.3.9"
  repository: https://helm.altinity.com/
  condition: clickhouse.enabled
  tags:
  - clickhouse
