apiVersion: v2
name: rybbit
description: A Helm chart for Rybbit self-hosted analytics
type: application
version: 1.3.0
appVersion: "2.8.0"
kubeVersion: ">=1.19.0-0"
maintainers:
- name: cade
  email: cade.ayres@riskidev.fi
  url: https://github.com/Riskidev
keywords:
- analytics
- self-hosted
- rybbit
home: https://github.com/Riskidev/rybbit-helm
sources:
- https://github.com/Riskidev/rybbit-helm

dependencies:
- name: valkey
  version: "0.11.0"
  repository: https://valkey-io.github.io/valkey-helm/
  condition: valkey.enabled
  tags:
  - valkey
