name: Publish Helm Chart

on:
  push:
    tags:
    - 'v*'

env:
  GHCR_REGISTRY: ghcr.io

jobs:
  lint:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Add Helm repositories
        run: |
          helm repo add cnpg https://cloudnative-pg.github.io/charts
          helm repo add altinity https://helm.altinity.com/
          helm repo update

      - name: Run Helm lint
        run: helm lint .

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2
        with:
          version: v3.10.0

      - name: Lint chart
        run: ct lint --config .github/ct-config.yaml --all

  template:
    name: Template Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Update dependencies
        run: helm dependency update

      - name: Template chart
        run: helm template test-release . --namespace test --debug

      - name: Template with custom values
        run: |
          helm template test-release . \
            --namespace test \
            --set backend.replicaCount=2 \
            --set client.replicaCount=2 \
            --set postgresql.cluster.instances=3 \
            --debug

  publish:
    name: Publish to GHCR
    runs-on: ubuntu-latest
    needs: [lint, template]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set version from tag
        run: |
          ref=${GITHUB_REF##*/}
          echo "VERSION=${ref#v}" >> $GITHUB_ENV
          echo "REPO_OWNER=$(echo "$GITHUB_REPOSITORY_OWNER" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "Publishing version: ${ref#v}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Update dependencies
        run: helm dependency update

      - name: Package Helm Chart
        run: helm package --version ${{ env.VERSION }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: |
          helm push rybbit-${{ env.VERSION }}.tgz oci://${{ env.GHCR_REGISTRY }}/${{ env.REPO_OWNER }}
          echo "Chart published: ${{ env.GHCR_REGISTRY }}/${{ env.REPO_OWNER }}/rybbit:${{ env.VERSION }}"
